### ISSUE TITLE
Current edge version of Zigbee-Herdsman preventing HA Addon to run

### ISSUE THREAD

**Issue by Jonno12345** [Koenkk/zigbee-herdsman#624] opened 2022-12-07 00:14 UTC
Hey,

Unfortunately didn't record the previous version I was on but it was roughly from the end of November, however I was wanting to try the latest TRV integration so updated my edge build. As of doing so, the edge version is now not starting, with the following log output:

```
[00:09:18] INFO: Preparing to start...
[00:09:18] INFO: Socat not enabled
[00:09:18] INFO: Zigbee Herdsman debug logging enabled
[00:09:20] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-12-07 00:09:25: Logging to console and directory: '/config/zigbee2mqtt/log/2022-12-07.00-09-25' filename: log.txt
Zigbee2MQTT:info  2022-12-07 00:09:25: Starting Zigbee2MQTT version 1.28.4-dev (commit #d075f07)
Zigbee2MQTT:info  2022-12-07 00:09:25: Starting zigbee-herdsman (0.14.78)
2022-12-07T00:09:25.586Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2022-12-07T00:09:25.590Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDD112A-if00"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2022-12-07T00:09:25.592Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with {"path":"/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDD112A-if00","baudRate":115200,"rtscts":false,"autoOpen":false}
```

This is as far as it gets, where it ceases to load any further. I cannot find any further log output stored anywhere but happy to retrieve if it could help.

In contrast, the exact same config on the latest production Z2M build gives the following log output and works correctly:

```
[00:14:31] INFO: Preparing to start...
[00:14:32] INFO: Socat not enabled
[00:14:32] INFO: Zigbee Herdsman debug logging enabled
[00:14:34] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-12-07 00:14:38: Logging to console and directory: '/config/zigbee2mqtt/log/2022-12-07.00-14-38' filename: log.txt
Zigbee2MQTT:info  2022-12-07 00:14:38: Starting Zigbee2MQTT version 1.28.4 (commit #unknown)
Zigbee2MQTT:info  2022-12-07 00:14:38: Starting zigbee-herdsman (0.14.76)
2022-12-07T00:14:39.284Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2022-12-07T00:14:39.288Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDD112A-if00"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2022-12-07T00:14:39.290Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDD112A-if00 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2022-12-07T00:14:39.304Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2022-12-07T00:14:39.308Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-12-07T00:14:39.311Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2022-12-07T00:14:39.326Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,1,121,1,26]

..etc..
```

**Comment by Koenkk** [comment] 2022-12-07 16:37
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/15380

**Closed by Koenkk** 2022-12-07 16:37 UTC
