### ISSUE TITLE
ZIGATE: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by biau** [Koenkk/zigbee-herdsman#285] opened 2021-01-10 16:35 UTC
## What happened
Using zigate I've an error after every module pairing:
```
info  2021-01-10 00:31:56: Configuring 'PriseChambre'
error 2021-01-10 00:32:00: Failed to configure 'PriseChambre', attempt 1 (TypeError: ConfigureReporting 0x7cb03eaa00b1a4a8/3 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Cannot read property 'length' of undefined)
    at Function.fromBuffer (/app/node_modules/zigbee-herdsman/dist/zcl/zclFrame.js:151:20)
    at ZiGateAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/zigate/adapter/zigateAdapter.js:524:50)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/adapter/zigate/adapter/zigateAdapter.js:24:58))

```
## What did you expect to happen
Pairing without error

## How to reproduce it (minimal and precise)
Just pair a device

## Debug info
Zigbee2MQTT version: 1.17.0
Adapter hardware: Zigate
Adapter firmware version: 3.1d

**Comment by Koenkk** [comment] 2021-01-10 16:41
Looks like a duplicate of https://github.com/Koenkk/zigbee-herdsman/issues/252#issuecomment-723579075

**Closed by Koenkk** 2021-01-10 16:41 UTC
